version: '3.3'

services:
  frontend:
    build: frontend/.
    image: frontend:latest
    ports:
      - 80:3000
    depends_on:
      - redis
      - backend
    env_file:
      - .env

  backend:
    build: backend/.
    image: backend:latest
    env_file:
      - .env
    ports:
      - 3080:3080
    depends_on:
      - redis

  e2e:
    build: e2e/.
    image: e2e:latest
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on:
      - redis
      - backend

  redis:
    image: redis:latest
    ports:
      - 6379:6379
